aidtec:
  dataset:
    filename: "train.csv"  # Dentro de data/aidtec en este caso
    label_col_name: "calidad"
    params:
      index_col: 0
  preprocessor:
    class_name: "WineDatasetTransformer"  # Dentro de data_processing/aidtec_transformer.py en este caso
    params:
      drop_columns:
        - "year"
        - "color"
        - "alcohol"
        - "densidad"
        - "dioxido de azufre libre"
  model:
    type: "sklearn.ensemble"  # poner el módulo en el que se encuentra el modelo
    class_name: "RandomForestClassifier"
    params:
      n_estimators: 900
      random_state: 42
  label_encoder: true

efficiency:
  dataset:
    filename: "train.csv"  # Dentro de data/efficiency
    label_col_name: "target"
  preprocessor:
    class_name: "EfficiencyTransformer"  # Dentro de data_processing/efficiency_transformer.py
  model:
    type: "sklearn.ensemble"  # poner el módulo en el que se encuentra el modelo
    class_name: "RandomForestClassifier"
    params:
      random_state: 42
      max_depth: 10
  label_encoder: false